### PR TITLE
Create Architecture.svg

### PR DESCRIPTION
**Pull request by suryarawat**
Added architecture block diagram to the repo

### CODE REVIEW

**Comment by suryarawat** [comment]
I added it to the repo because we need the link to be added so maybe keeping it here in repo would be best. Although, maybe merge to main is not required

**Comment by mdangnguyen** [comment]
I see. Does it still work if we close the PR?

**Comment by suryarawat** [comment]
> I see. Does it still work if we close the PR?

It should, it's separate branch data

**Comment by mdangnguyen** [comment]
Ok, then can you close this PR? It's weird just having this here

**Pull request closed without merging**
