### PR TITLE
Added Objective section to README

### PR DESCRIPTION
**Pull request by mdangnguyen**

### CODE REVIEW

**Review by hasan-umanitoba — APPROVED** [review]

**Comment by hasan-umanitoba** [comment]
You could also further add at the start at the description para if you wish to.  "We aim to build a web application for Comp 4350 course.  To fulfill the goal of the project we leverage agile methodology to build Digital Deck .... ".

**Comment by mdangnguyen** [comment]
Yeah I don't think we need to mention that in the description.

**Comment by suryarawat** [comment]
Maybe a line regarding the scope of the project for this term? Like our objective is to have at least 2 user stories finished by the end of course. I guess since objective could be objective of this course project. Otherwise, if you think it's good enough I am approving it and you can merge it.

**Comment by mdangnguyen** [comment]
I believe we have to finish all of our user stories for the core features, so I don't think we need to state that. It feels weird because objective and description covers more or less the same info so I'm not sure what else to put

**Pull request merged**
